text = input("Add some text: ")
x = input("Choose first letter: ")
y = input("Choose second letter: ")
z = input("Choose third letter: ")
text = text.lower()
x = x.lower()
y = y.lower()
z = z.lower()
listText = text.split(" ")
print(f"The first letter '{x}' that you choose appers: {text.count(x)} times")
print(f"The second letter '{y}' that you choose appers: {text.count(y)} times")
print(f"The third letter '{z}' that you choose appers: {text.count(z)} times")
print(f"Total of words: {len(listText)}")
print(f"First letter: {text[0]}")
print(f"Last leter: {text[-1]}")
print(f"Text inverted: {text[::-1]}")
print(f"The word 'python' appers in the text? {'Si' if 'python' in listText else 'No'}")